### ISSUE TITLE
UMRELLA: Move Cluster API provider for DigitalOcean to Upstream

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#105]
**User story**

On Cluster-API meetings held on 8/22 and 9/19, we have discussed about making Cluster API provider for DigitalOcean as an Cluster-API project and moving it from `kubermatic` to `kubernetes-sigs` organization.

The feedback overall is positive, but we need to fulfill the ownership requirement. The latest requirement is to have multiple owners from the multiple companies.

It is up to follow on this issue and to discuss how we can continue the process.

**Prerequisites**

- [x] Add CONTRIBUTING.md (#91)
- [x] Establish OWNERS and OWNER_ALIASES files (#107, #112)
- [x] Add SECURITY_CONTACTS file (#108)
- [x] Add copyright boiler plate header to all files (#110) 
- [x] Add script to verify boilerplate header (#111)   
- [ ] License Auditing
- [x] Creating an issue on kubernetes/org (https://github.com/kubernetes/org/issues/196)
- [x] Enabling the Circle CI status contexts as required in kubernetes/test-infra (https://github.com/kubernetes/test-infra/pull/9938)
- [x] Update prow/config.yaml in kubernetes/test-infra to set merge method (https://github.com/kubernetes/test-infra/pull/9938)
- [x] Disable integration with Kubermatic internal Prow
- [x] Ensure relevant webhooks are enabled.
   - [x] cncf-cla webhook
   - [x] prow's webhook
- [ ] Update CONTRIBUTING.md to mention Kubernetes slack channels.
- [ ] Find how to correctly handle Docker images
- [x] Update README and docs to use new repository URL
- [x] Update Go import paths to `sigs.k8s.io/cluster-api-provider-digitalocean/...`
- [x] Update sigs.yaml file in kubernetes/community (https://github.com/kubernetes/community/pull/2864)

**Acceptance criteria**

- [ ] Cluster-API provider for DigitalOcean is upstreamed.

**Comment by xmudrii** [comment]
Testing does Prow works after migration.

/meow boxes

**Comment by xmudrii** [comment]
Relevant webhooks (Prow and CNCF CLA check) are enabled at the organization level.

CircleCI is enabled, but we need to make contexts work. The plan is to move to Prow as soon as possible.

I've updated issue with some more points that we should resolve before considering migration done.

**Comment by xmudrii** [comment]
@nikhita Is it okay to close this issue? I'm going to take care of updating the contributing guidelines later today and we can create a follow up for license auditing.

**Comment by nikhita** [comment]
Sgtm.

/close
