### ISSUE TITLE
Add prowjob for e2e test

### ISSUE THREAD

**Issue by nikhita** [kubernetes-sigs/cluster-api-provider-digitalocean#121]
We have prowjobs for most of the circleci tests except the e2e test because the e2e test is more nuanced.

**TODO**:

- [ ] Discuss how prowjobs for the e2e test should behave.
- [ ] Create a PR against the kubernetes/test-infra repo to add the prowjob.
- [ ] Verify that the test runs correctly.

/cc @xmudrii
