### ISSUE TITLE
Migrate to CRDs

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#83]
Upstream Cluster-API has moved from aggregated API servers to CRDs-based approach. This issue contains task needed to be done in order to switch to CRDs.

Relevant PR: https://github.com/kubernetes-sigs/cluster-api/pull/494

**Tasks:**

* [x] Move clusterctl into cmd/clusterctl (#123)
* [x] Move cloud into pkg (#124)
* [ ] Remove cluster and machine actuators (#125) 
* [ ] Update Cluster-API to CRDs version (#126)
* [ ] Update Cluster-API to the latest version once CRDs start working (#126)
