### ISSUE TITLE
UMBRELLA: Cluster Actuator

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#95]
Issue for discussions about Cluster Actuator.

For now we don't have Cluster Controller/Actuator implemented neither we deploy cluster controller on clusters.

The reasoning behind that is that there are no appropriate resources to be managed by cluster controller at this point.

Potentially, cluster controller could manage:

- [ ] IP addresses - Making sure API endpoints for cluster are correct, as well as could manage Floating IPs.
- [ ] Tags - clean up tags related to the cluster if they're empty.
- [ ] Firewalls - Allow users to create a Firewall to additionally protect a cluster. Problem here is that users would have to manually open ports needed by their applications, as DO CCM doesn't handle that. This is a planned feature for CCM.

**Comment by xmudrii** [comment]
The cluster actuator is not needed at all for DO provider at this point.

/close
